import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navegation from "@/components/navigation";
import Footer from "@/components/footer";
import Header from "../components/header"
// import { CartProvider } from "../context/cart-context"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen antialiased">
        {/* <CartProvider> */}

        <Header/>
        <Navegation/>
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
        {/* </CartProvider> */}
      </body>
    </html>
  );
}
